## **EKG Arrhythmia Detection Machine Learning Model**
#### Spandan Das

##### This notebook is a python model that takes an EKG (Electrocardiogram) data as input & determines if the EKG reflects a patient with cardiac arrhythmia or not; if diagnosed with arrhythmia the model classifies the type of arrhythmia: Atrial Fibrillation (AFib), Tachycardia, or Bradycardia.





In [ ]:
import numpy as np
# Import necessary packages

#### This is the **First Neural Network** that will identify whether an EKG is Arrhythmic or Normal.

##### Choosing a normalizing function is a critical step to creating any neural network. A normalizing function is a function that creates a common scale for all outputs of the function.

##### Since there are different types of normalizing functions we chose a function that lets us distinguish our output on a scale of zero to one, which is essentially a sigmoid normalizing function.

##### Additionally the sigmoid derivative needs to be calculated as this will be used for our synaptic weight adjustments (will be defined later on in this document).

In [ ]:
def sigmoid(x):
  # Define the normalizing function, in this context a sigmoid function
  return 1 / (1 + np.exp(-x))
  # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

def sigmoid_derivative(x):
  # Define the sigmoid derivative
  return x * (1 - x)
  # The derivative of the sigmoid function in terms of x

##### Now that the sigmoid normailizing function has been set we can define the training example.

##### Any machine learning (ML) model requires a training example. The training example is the data that is used to train the ML model to predict the desired outputs. By feeding a series of inputs as well as their known outputs into the ML model the program is able to identify patterns in the input data that lead to the respective output.

##### In this neural network our training example will consist of two types of data, Arrhythmic EKG data & Normal EKG data. Both these types of data will be pulled from a published Arrhythmia EKG dataset found [here](https://datahub.io/machine-learning/arrhythmia/r/arrhythmia.csv).

In [ ]:
training_inputs_nn1 = np.array([[44, 175, 42],
                                [82, 154, 94],
                                [115, 0, 0],
                                [85, 203, 102],
                                [75, 0, 0],
                                [71, 0, 0],
                                [98, 0, 0],
                                [59, 163, 106],
                                [163, 126, 60],
                                [49, 145, 101],
                                [71, 202, 143],
                                [90, 0, 0],
                                [60, 155, 118],
                                [92, 137, 92],
                                [113, 0, 0],
                                [103, 169, 85],
                                [76, 251, 183],
                                [40, 170, 102],
                                [124, 155, 64],
                                [32, 162, 95,],
                                [112, 0, 0],
                                [85, 167, 355],
                                [67, 143, 70],
                                [91, 154, 96],
                                [73, 135, 80],
                                [81, 0, 0],
                                [94, 156, 97],
                                [86, 153, 90],
                                [122, 204, 72],
                                [102, 224, 122],
                                [66, 181, 79],
                                [42, 192, 101],
                                [112, 178, 117],
                                [68, 140, 82],
                                [92, 158, 103],
                                [85, 147, 96],
                                [81, 155, 104],
                                [93, 150, 96],
                                [93, 125, 63],
                                [81, 0, 0],
                                [104, 0, 0],
                                [101, 172, 90],
                                [77, 132, 82],
                                [98, 195, 102],
                                [56, 180, 104],
                                [75, 185, 107],
                                [64, 118, 63],
                                [53, 228, 94],
                                [117, 141, 79],
                                [92, 160, 101],
                                [69, 157, 92],
                                [79, 177, 113],
                                [66, 122, 78],
                                [58, 174, 39],
                                [101, 136, 82],
                                [51, 157, 91],
                                [76, 132, 65],
                                [66, 154, 83],
                                [104, 121, 67],
                                [81, 136, 76],
                                [86, 159, 117],
                                [72, 143, 65],
                                [100, 156, 172],
                                [101, 147, 155],
                                [99, 151, 166],
                                [102, 158, 177],
                                [98, 142, 137],
                                [97, 170, 152],
                                [102, 156, 173],
                                [104, 142, 159],
                                [108, 135, 247],
                                [112, 168, 149],
                                [99, 143, 218],
                                [98, 199, 154],
                                [110, 147, 159],
                                [110, 135, 238],
                                [100, 139, 152],
                                [103, 142, 160],
                                [99, 106, 218],
                                [57, 157, 92],
                                [58, 163, 106],
                                [59, 228, 94]])
# Training inputs are organized in a array within a 6x62 matrix
# Each array within the matrix is a set of inputs from the dataset
# Each input within the array is specific EKG variable as shown below:
# [Heart Rate, QRS Duration, PR Interval, T Interval, P Interval, QT Interval]

training_outputs_nn1 = np.array([[1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1]]).T
# Training outputs are organized in an array which has been transposed to a 62x1 matrix
# The first value of the output's array is the respective output for the input's first array
# An output of 0 signifies the EKG is Normal
# An output of 1 signifies the EKG is Arrhythmic

##### The next step after defining our training example is to initialize our weights.

##### As metioned previously, a neural network needs to be able to identify patterns in the input data that lead to the respective output. In order for the neural network to be able to accurately predict whether the input data yields 0 or 1, we need to initialize weights. Weights are the values that are assigned to each input when being run through our sigmoid normalizing function (aka synaptic weights). The weights are then adjusted to yield the right output based on the error calculations (error calculations will be further explained below).

##### Simply put, the synaptic weights are what are adjusted to determine which inputs from the EKG yield the correct output.

In [ ]:
synaptic_weights_nn1 = 2 * np.random.random((3,1)) - 1
# We don't know each input's significance on the output, therefore we will assign random weights
# Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
# The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1

print('Synaptic Weights Prior Training:')
print(synaptic_weights_nn1)
# Printing the synaptic weights prior training will allow us to compare the weights post training

Synaptic Weights Prior Training:
[[ 0.63810415]
 [ 0.76665627]
 [-0.49230705]]


##### Since our normalizing function has been defined, training examples have been organized, and our synaptic weights have been intialized, we can finally start training the model.

##### Before we can begin training our model, understanding the architecture of our neural network is key. The architecture of our neural network consists of 4 features: inputs, synapses, neuron & output. The inputs in this neural network are the various values collected from a EKG. The synapses are the connections between the inputs and the neuron. The neuron is the sigmoid normalizing function that predicts our output. Finally our output is a range from 0 to 1, with any value close to zero resembling a normal EKG and any value close to 1 resembling an arrhythmic EKG. This neural network architecture has been pictured [here](https://drive.google.com/file/d/1HDXbnD7nKK7ZIM13lbX1IFDtUzrFgsL9/view?usp=sharing).

##### Training the model in ML is when synaptic weights are readjusted, according to the severeness of the error calculation. The error calculation is derived by calculating the difference between the model's predicted output of the traning data and the traing data's true output. Every time the model readjusts the synaptic weights we consider that a single iteration. The model keeps on running multiple iterations, until the model is able to accurately predict the correct output for the training data.

#### In order to figure out the magnitude by which each weight should be adjusted based of the error calculation we need to calculate the error weighted derivative. The error weighted derivative is product of the error (output - actual output), the input and the derivative of the sigmoid function at our output. The process of readjusting the weights based of the error calculations is called backpropagation. Do note that due to the high number of iterations the cell below takes 45-60 seconds on average to process an output, additional time may be needed if internet connection is weak.

In [ ]:
for iteration in range(50000):
# Embeding the code below in a for loop allows us to run multiple iterations
# The value in range is the total number of iterations we want to run

  input_layer_nn1 = training_inputs_nn1
  # Relabelling training inputs as input layer to distinguish the inputs

  outputs_nn1 = sigmoid(np.dot(input_layer_nn1, synaptic_weights_nn1))
  # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
  # By using np.dot we can multiply the synaptic weight by the array of inputs

  error_nn1 = training_outputs_nn1 - outputs_nn1
  # The error is the difference between output and actual output

  weight_adjustments_nn1 = error_nn1 * sigmoid_derivative(outputs_nn1)
  # Calculated by multiplying the error and the sigmoid derivative

  synaptic_weights_nn1 += np.dot(input_layer_nn1.T, weight_adjustments_nn1)
  # Input layer must be transposed to match array
  # By using np.dot we can multiply the weight adjustments by the input layer array

  print('Synaptic Weights Post Training:')
  print(synaptic_weights_nn1)
  # Printing the synaptic weights post training will allow us to compare the weights prior training


Synaptic Weights Post Training:
[[ 0.59123776]
 [ 0.67457758]
 [-0.68804318]]
Synaptic Weights Post Training:
[[-0.00782283]
 [-0.20209265]
 [-2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[

<ipython-input-37-12c9cfcf4c88>:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


Streaming output truncated to the last 5000 lines.
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.20209265]
 [ -2.00919075]]
Synaptic Weights Post Training:
[[138.40108116]
 [ -0.2020



##### The set of values printed above are the synaptic weights post training. Let's compare the synaptic weigths.

##### The synaptic weights prior to training were set to be random as we didn't know what variables contribute to arrhythmia. However if we look at the values of the synpaptic weigths after training the values have been ranked with the most significant contributer having the highest numerical synaptic weight.

##### After running the necessary number of iterations we have derived the appropriate synaptic weights. This means we can finally pass inputs (EKG variables) with an unknown classification of normal EKG or arrhythmic EKG and have the nueral network predict whether the EKG is normal or arrhythmic.

##### In order to pass our own inputs through our neural network we need to define a function where we can type our own values in for each EKG variable.

In [ ]:
def compute(self, inputs):
# Defining the function that will be used to type in our own EKG values

  inputs = inputs.astype(float)
  # Since our inputs are integers we need to convert them to a float, to match our synaptic weights

  output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
  # By using np.dot we can multiply the arrays of inputs and the synaptic weights
  # The product can then be plugged into the sigmoid function to calculate the output

  return output

##### Although we want to run our own EKG inputs through our nueral network we need to rewrite all the code above within a class in order to be able to input our own EKG Values. Since we are limited by the cell layout of Google Collab, even though it is inefficient, the most appropriate solution is to rewrite all the code above into a class in one code cell. This also requires us to treat many vairables as objects. Additionally by using if statements and operators we have the model print out what the EKG reflects: Arhhythmic or Normal. This has been done below. Do note due to the high number of iterations the cell below takes 45-60 seconds on average to process an output, additional time may be needed if internet connection is weak.

In [ ]:
class neural_network_1():

    def __init__(self):
    # We are initializing the object's attributes

        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
        # We don't know each input's significance on the output, therefore we will assign random weights
        # Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
        # The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1


    def sigmoid(self, x):
    # Define the normalizing function, in this context a sigmoid function

        return 1 / (1 + np.exp(-x))
        # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

    def sigmoid_derivative(self, x):
    # Define the sigmoid derivative

        return x * (1 - x)
        # The derivative of the sigmoid function in terms of x

    def train(self, training_inputs, training_outputs):
    # Define a function to run training data

        for iteration in range(500000):
        # Embeding the code below in a for loop allows us to run multiple iterations
        # The value in range is the total number of iterations we want to run

            output_nn1 = sigmoid(np.dot(input_layer_nn1, synaptic_weights_nn1))
            # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
            # By using np.dot we can multiply the synaptic weight by the array of inputs

            error_nn1 = training_outputs - output_nn1
            # The error is the difference between output and actual output

            weights_nn1 = error_nn1 * self.sigmoid_derivative(output_nn1)
            # Calculated by multiplying the error and the sigmoid derivative

            weight_adjustments_nn1 = np.dot(training_inputs.T, weights_nn1)
            # Training inputs must be transposed to match array
            # By using np.dot we can multiply the training inputs by the weights


            self.synaptic_weights += weight_adjustments_nn1
            # Adjust the weights accordiningly

            training_inputs_nn1 = np.array([[44, 175, 42],
                                            [82, 154, 94],
                                            [115, 0, 0],
                                            [85, 203, 102],
                                            [75, 0, 0],
                                            [71, 0, 0],
                                            [98, 0, 0],
                                            [59, 163, 106],
                                            [163, 126, 60],
                                            [49, 145, 101],
                                            [71, 202, 143],
                                            [90, 0, 0],
                                            [60, 155, 118],
                                            [92, 137, 92],
                                            [113, 0, 0],
                                            [103, 169, 85],
                                            [76, 251, 183],
                                            [40, 170, 102],
                                            [124, 155, 64],
                                            [32, 162, 95,],
                                            [112, 0, 0],
                                            [85, 167, 355],
                                            [67, 143, 70],
                                            [91, 154, 96],
                                            [73, 135, 80],
                                            [81, 0, 0],
                                            [94, 156, 97],
                                            [86, 153, 90],
                                            [122, 204, 72],
                                            [102, 224, 122],
                                            [66, 181, 79],
                                            [42, 192, 101],
                                            [112, 178, 117],
                                            [68, 140, 82],
                                            [92, 158, 103],
                                            [85, 147, 96],
                                            [81, 155, 104],
                                            [93, 150, 96],
                                            [93, 125, 63],
                                            [81, 0, 0],
                                            [104, 0, 0],
                                            [101, 172, 90],
                                            [77, 132, 82],
                                            [98, 195, 102],
                                            [56, 180, 104],
                                            [75, 185, 107],
                                            [64, 118, 63],
                                            [53, 228, 94],
                                            [117, 141, 79],
                                            [92, 160, 101],
                                            [69, 157, 92],
                                            [79, 177, 113],
                                            [66, 122, 78],
                                            [58, 174, 39],
                                            [101, 136, 82],
                                            [51, 157, 91],
                                            [76, 132, 65],
                                            [66, 154, 83],
                                            [104, 121, 67],
                                            [81, 136, 76],
                                            [86, 159, 117],
                                            [72, 143, 65],
                                            [100, 156, 172],
                                            [101, 147, 155],
                                            [99, 151, 166],
                                            [102, 158, 177],
                                            [98, 142, 137],
                                            [97, 170, 152],
                                            [102, 156, 173],
                                            [104, 142, 159],
                                            [108, 135, 247],
                                            [112, 168, 149],
                                            [99, 143, 218],
                                            [98, 199, 154],
                                            [110, 147, 159],
                                            [110, 135, 238],
                                            [100, 139, 152],
                                            [103, 142, 160],
                                            [99, 106, 218],
                                            [57, 157, 92],
                                            [58, 163, 106],
                                            [59, 228, 94]])
            # Training inputs are organized in a array within a 3x62 matrix
            # Each array within the matrix is a set of inputs from the dataset
            # Each input within the array is specific EKG variable as shown below:
            # [Heart Rate, QRS Duration, PR Interval, T Interval, P Interval, QT Interval]

            training_outputs_nn1 = np.array([[1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1]]).T
            # Training outputs are organized in an array which has been transposed to a 62x1 matrix
            # The first value of the output's array is the respective output for the input's first array
            # An output of 0 signifies the EKG is Normal
            # An output of 1 signifies the EKG is Arrhythmic

    def compute(self, inputs):
    # Define compute function which allows to pass new EKG values through the neural network

        inputs = inputs.astype(float)
        # Since weights are floats all inputs need to be floats as well

        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        # Run the inputs through the sigmoid function after weight adjustment

        return output


neural_network = neural_network_1()
# Rename neural network class to neural network for ease of use

neural_network.train(training_inputs_nn1, training_outputs_nn1)
# Intializes the training of the training data


heart_rate = str(input("Heart Rate: "))
# Allows us to type in our own heart rate input

PR_interval = str(input("PR Interval: "))
# Allows us to type in our own PR interval input

P_interval = str(input("P Interval: "))
# Allows us to type in our own P interval input



print("Output:")

final_output = (neural_network.compute(np.array([heart_rate, PR_interval, P_interval])))
# Computes new EKG inputs and classifies it either 0 or 1

print(final_output)
# Prints the final value on a scale of 0 and 1

if final_output < 0.2:
  print('EKG is Normal')
  # Prints EKG is Normal if value less than 0.2

if final_output > 0.8:
  print('EKG is Arrhythmic')
  # Prints EKG is Arrhythmic if value greater than 0.8

Heart Rate: 75
PR Interval: 127
P Interval: 78
Output:
[4.37512433e-52]
EKG is Normal


##### The first neural network is now able successfully identified whether an EKG is normal or arrhythmic. If the EKG is arrhythmic we need to identify whether the arrhythmic EKG reflects atrial fibrillation or tachycardia/bradicardia. That is the role of the second neural network: distiguishing between atrial fibrillation or tachycardia/bradicardia.

#### This is the **Second Neural Network** that will identify whether an arrhytmic EKG is atrial fibrillation or tachycardia/bradycardia.
##### Do note that a majority of the code will be similar to the code in the first neural network, with the biggest change being the training data.

##### As always the first step is to choose a normalizing function. Since we will be distiguishing between two outputs on a scale of zero to one we will use the same normalizing function, a sigmoid normalizing function, as we did in the first neural network. Aditionally we will need to calculate the sigmoid derivative for our synaptic weight adjustments, like done before.

In [ ]:
def sigmoid(x):
  # Define the normalizing function, in this context a sigmoid function
  return 1 / (1 + np.exp(-x))
  # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

def sigmoid_derivative(x):
  # Define the sigmoid derivative
  return x * (1 - x)
  # The derivative of the sigmoid function in terms of x

##### Now that the sigmoid normailizing function has been set we can define the training example.

##### For the second neural network our training example will consist of two types of data, Atrial Fibrilatiion EKG data & Tachycardia/Bradycardia EKG data. Both these types of data will be pulled from the published Arrhythmia EKG dataset found [here](https://datahub.io/machine-learning/arrhythmia/r/arrhythmia.csv).

In [ ]:
training_inputs_nn2 = np.array([[44, 175, 42],
                                [115, 0, 0],
                                [75, 0, 0],
                                [71, 0, 0],
                                [98, 0, 0],
                                [59, 163, 106],
                                [163, 126, 60],
                                [49, 145, 101],
                                [90, 0, 0],
                                [113, 0, 0],
                                [103, 169, 85],
                                [40, 170, 102],
                                [124, 155, 64],
                                [32, 162, 95],
                                [112, 0, 0],
                                [81, 0, 0],
                                [122, 204, 72],
                                [102, 224, 122],
                                [42, 192, 101],
                                [112, 178, 117],
                                [81, 0, 0],
                                [104, 0, 0],
                                [101, 172, 90],
                                [56, 180, 104],
                                [53, 228, 94],
                                [76, 0, 0],
                                [117, 141, 79],
                                [58, 174, 39],
                                [101, 136, 82],
                                [51, 157, 91],
                                [104, 121, 67],
                                [82, 0, 0],
                                [101, 0, 0],
                                [52, 0, 0],
                                [100, 156, 172],
                                [101, 147, 155],
                                [102, 0, 0],
                                [71, 0, 0],
                                [91, 0, 0],
                                [102, 158, 177],
                                [102, 156, 173],
                                [66, 0, 0],
                                [78, 0, 0],
                                [58, 0, 0],
                                [67, 0, 0],
                                [78, 0, 0],
                                [89, 0, 0],
                                [99, 0, 0],
                                [82, 0, 0],
                                [104, 142, 159],
                                [108, 135, 247],
                                [112, 168, 149],
                                [93, 0, 0],
                                [91, 0, 0],
                                [86, 0, 0],
                                [110, 147, 159],
                                [110, 135, 238],
                                [100, 139, 152],
                                [89, 0, 0],
                                [103, 142, 160],
                                [57, 157, 92],
                                [58, 163, 106],
                                [59, 228, 94]])
# Training inputs are organized in a array within a 6x10 matrix
# Each array within the matrix is a set of inputs from the dataset
# Each input within the array is specific EKG variable as shown below:
# [Heart Rate, QRS Duration, PR Interval, T Interval, P Interval, QT Interval]

training_outputs_nn2 = np.array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1]]).T
# Training outputs are organized in an array which has been transposed to a 10x1 matrix
# The first value of the output's array is the respective output for the input's first array
# An output of 0 signifies the EKG is Atrial Fibrillation
# An output of 1 signifies the EKG is Tachycardia/Bradycardia

##### The next step after defining our training example is to initialize our weights, like accomplished in the first neural network.

In [ ]:
synaptic_weights_nn2 = 2 * np.random.random((3,1)) - 1
# We don't know each input's significance on the output, therefore we will assign random weights
# Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
# The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1

print('Synaptic Weights Prior Training:')
print(synaptic_weights_nn2)
# Printing the synaptic weights prior training will allow us to compare the weights post training

Synaptic Weights Prior Training:
[[-0.17850689]
 [ 0.14752852]
 [ 0.82651682]]


##### Since our normalizing function has been defined, training examples have been organized, and our synaptic weights have been intialized, we can start training the second model.

###### Once again our architecture of our neural network and method of error calculations will remain the same as the first neural netowrk. The architecture of our neural network consists of 4 features: inputs, synapses, neuron & output. The inputs in this neural network are the various values collected from a EKG. The synapses are the connections between the inputs and the neuron. The neuron is the sigmoid normalizing function that predicts our output. Finally our output is a range from 0 to 1, with any value close to zero resembling a Atrial Fibrillation EKG and any value close to 1 resembling an Tachycardiac/Bradycardiac EKG. This neural network architecture has been pictured [here](https://drive.google.com/file/d/1HDXbnD7nKK7ZIM13lbX1IFDtUzrFgsL9/view?usp=sharing).

In [ ]:
for iteration in range(50000):
# Embeding the code below in a for loop allows us to run multiple iterations
# The value in range is the total number of iterations we want to run

  input_layer_nn2 = training_inputs_nn2
  # Relabelling training inputs as input layer to distinguish the inputs

  outputs_nn2 = sigmoid(np.dot(input_layer_nn2, synaptic_weights_nn2))
  # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
  # By using np.dot we can multiply the synaptic weight by the array of inputs

  error_nn2 = training_outputs_nn2 - outputs_nn2
  # The error is the difference between output and actual output

  weight_adjustments_nn2 = error_nn2 * sigmoid_derivative(outputs_nn2)
  # Calculated by multiplying the error and the sigmoid derivative

  synaptic_weights_nn2 += np.dot(input_layer_nn2.T, weight_adjustments_nn2)
  # Input layer must be transposed to match array
  # By using np.dot we can multiply the weight adjustments by the input layer array

  print('Synaptic Weights Post Training:')
  print(synaptic_weights_nn2)
  # Printing the synaptic weights post training will allow us to compare the weights prior training

Streaming output truncated to the last 5000 lines.
Synaptic Weights Post Training:
[[-0.19079768]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079782]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079797]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079811]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079825]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079839]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079853]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079867]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079881]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079895]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.1907991 ]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weights Post Training:
[[-0.19079924]
 [ 0.14752852]
 [ 0.82651682]]
Synaptic Weig

##### The set of values printed above are the synaptic weights post training. Let's compare the synaptic weigths.

##### The synaptic weights prior to training were set to be random as we didn't know what variables contribute to atrial fibrillation or tachycardia/bradycardia. However if we look at the values of the synpaptic weigths after training the values have been ranked with the most significant contributer having the highest numerical synaptic weight.

##### After running the necessary number of iterations we have derived the appropriate synaptic weights. This means we can finally pass inputs (EKG variables) with an unknown classification of atrial fibrillation EKG or tachycardia/bradycardia EKG and have the nueral network predict whether the EKG is atrial fibrillation or tachycardia/bradycardia.

##### In order to pass our inputs inserted through our first neural network through the second neural network we need to define a function where we can pull the EKG values from the first neural network.

In [ ]:
def compute(self, inputs):
# Defining the function that will be used to type in our own EKG values

  inputs = inputs.astype(float)
  # Since our inputs are integers we need to convert them to a float, to match our synaptic weights

  output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
  # By using np.dot we can multiply the arrays of inputs and the synaptic weights
  # The product can then be plugged into the sigmoid function to calculate the output

  return output

##### Although we want to run the same EKG inputs from our first neural network through our second nueral network we need to rewrite all the code for the second neural network within a class in order to be re-run our own EKG Values. Since we are limited by the cell layout of Google Collab, even though it is inefficient, the most appropriate solution is to rewrite the code for the second neuron above into a class in one code cell. This also requires us to treat many vairables as objects. Additionally by using if statements and operators we have the model print out what the EKG reflects: Atrial Fibrillation or Tachycardia/Bradycardia. This has been done below.

In [ ]:
class neural_network_2():

    def __init__(self):
    # We are initializing the object's attributes

        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
        # We don't know each input's significance on the output, therefore we will assign random weights
        # Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
        # The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1


    def sigmoid(self, x):
    # Define the normalizing function, in this context a sigmoid function

        return 1 / (1 + np.exp(-x))
        # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

    def sigmoid_derivative(self, x):
    # Define the sigmoid derivative

        return x * (1 - x)
        # The derivative of the sigmoid function in terms of x

    def train(self, training_inputs, training_outputs):
    # Define a function to run training data

        for iteration in range(500000):
        # Embeding the code below in a for loop allows us to run multiple iterations
        # The value in range is the total number of iterations we want to run

            output_nn2 = sigmoid(np.dot(input_layer_nn2, synaptic_weights_nn2))
            # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
            # By using np.dot we can multiply the synaptic weight by the array of inputs

            error_nn2 = training_outputs - output_nn2
            # The error is the difference between output and actual output

            weights_nn2 = error_nn2 * self.sigmoid_derivative(output_nn2)
            # Calculated by multiplying the error and the sigmoid derivative

            weight_adjustments_nn2 = np.dot(training_inputs.T, weights_nn2)
            # Training inputs must be transposed to match array
            # By using np.dot we can multiply the training inputs by the weights


            self.synaptic_weights += weight_adjustments_nn2
            # Adjust the weights accordiningly

            training_inputs_nn2 = np.array([[44, 175, 42],
                                            [115, 0, 0],
                                            [75, 0, 0],
                                            [71, 0, 0],
                                            [98, 0, 0],
                                            [59, 163, 106],
                                            [163, 126, 60],
                                            [49, 145, 101],
                                            [90, 0, 0],
                                            [113, 0, 0],
                                            [103, 169, 85],
                                            [40, 170, 102],
                                            [124, 155, 64],
                                            [32, 162, 95],
                                            [112, 0, 0],
                                            [81, 0, 0],
                                            [122, 204, 72],
                                            [102, 224, 122],
                                            [42, 192, 101],
                                            [112, 178, 117],
                                            [81, 0, 0],
                                            [104, 0, 0],
                                            [101, 172, 90],
                                            [56, 180, 104],
                                            [53, 228, 94],
                                            [76, 0, 0],
                                            [117, 141, 79],
                                            [58, 174, 39],
                                            [101, 136, 82],
                                            [51, 157, 91],
                                            [104, 121, 67],
                                            [82, 0, 0],
                                            [101, 0, 0],
                                            [52, 0, 0],
                                            [100, 156, 172],
                                            [101, 147, 155],
                                            [102, 0, 0],
                                            [71, 0, 0],
                                            [91, 0, 0],
                                            [102, 158, 177],
                                            [102, 156, 173],
                                            [66, 0, 0],
                                            [78, 0, 0],
                                            [58, 0, 0],
                                            [67, 0, 0],
                                            [78, 0, 0],
                                            [89, 0, 0],
                                            [99, 0, 0],
                                            [82, 0, 0],
                                            [104, 142, 159],
                                            [108, 135, 247],
                                            [112, 168, 149],
                                            [93, 0, 0],
                                            [91, 0, 0],
                                            [86, 0, 0],
                                            [110, 147, 159],
                                            [110, 135, 238],
                                            [100, 139, 152],
                                            [89, 0, 0],
                                            [103, 142, 160],
                                            [57, 157, 92],
                                            [58, 163, 106],
                                            [59, 228, 94]])
            # Training inputs are organized in a array within a 3x63 matrix
            # Each array within the matrix is a set of inputs from the dataset
            # Each input within the array is specific EKG variable as shown below:
            # [Heart Rate, QRS Duration, PR Interval, T Interval, P Interval, QT Interval]

            training_outputs_nn2 = np.array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1]]).T
            # Training outputs are organized in an array which has been transposed to a 63x1 matrix
            # The first value of the output's array is the respective output for the input's first array
            # An output of 0 signifies the EKG is Atrial Fibrillation
            # An output of 1 signifies the EKG is Tachycardia/Bradycardia

    def compute(self, inputs):
    # Define compute function which allows to pass new EKG values through the neural network

        inputs = inputs.astype(float)
        # Since weights are floats all inputs need to be floats as well

        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        # Run the inputs through the sigmoid function after weight adjustment

        return output


neural_network = neural_network_2()
# Rename neural network class to neural network for ease of use

neural_network.train(training_inputs_nn2, training_outputs_nn2)
# Intializes the training of the training data


print("Output:")

final_output = (neural_network.compute(np.array([heart_rate, PR_interval, P_interval])))
# Computes new EKG inputs and classifies it either 0 or 1

print(final_output)
# Prints the final value on a scale of 0 and 1

if final_output < 0.2:
  print('EKG is Atrial Fibrillation')
  # Prints EKG is Atrial Fibrillation if value less than 0.2

if final_output > 0.8:
  print('EKG is Tachycardic/Bradycardic')
  # Prints EKG is Tachycardic/Bradycardic if value greater than 0.8

Output:
[1.]
EKG is Tachycardic/Bradycardic


#### This is the **Third Neural Network** that will identify whether an arrhytmic EKG is tachycardia or bradycardia.
##### Do note that a majority of the code will be similar to the code in the first and second neural network, with the biggest change being the training data.  

##### As always the first step is to choose a normalizing function. Since we will be distiguishing between two outputs on a scale of zero to one we will use the same normalizing function, a sigmoid normalizing function, as we did in the previous neural networks. Aditionally we will need to calculate the sigmoid derivative for our synaptic weight adjustments, like done before.

In [ ]:
def sigmoid(x):
  # Define the normalizing function, in this context a sigmoid function
  return 1 / (1 + np.exp(-x))
  # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

def sigmoid_derivative(x):
  # Define the sigmoid derivative
  return x * (1 - x)
  # The derivative of the sigmoid function in terms of x

##### Now that the sigmoid normailizing function has been set we can define the training example.

##### For the third neural network our training example will consist of two types of data, Tachycardia EKG data & Bradycardia EKG data. Both these types of data will be pulled from the published Arrhythmia EKG dataset found [here](https://datahub.io/machine-learning/arrhythmia/r/arrhythmia.csv).

In [ ]:
training_inputs_nn3 = np.array([[44, 175, 42],
                                [59, 163, 106],
                                [163, 126, 60],
                                [49, 145, 101],
                                [103, 169, 85],
                                [40, 170, 102],
                                [124, 155, 64],
                                [32, 162, 95],
                                [122, 204, 72],
                                [102, 224, 122],
                                [42, 192, 101],
                                [112, 178, 117],
                                [101, 172, 90],
                                [56, 180, 104],
                                [53, 228, 94],
                                [117, 141, 79],
                                [58, 174, 39],
                                [101, 136, 82],
                                [51, 157, 91],
                                [104, 121, 67],
                                [100, 156, 172],
                                [55, 133, 101],
                                [56, 148, 93],
                                [101, 147, 155],
                                [102, 158, 177],
                                [50, 180, 68],
                                [57, 142, 91],
                                [102, 156, 173],
                                [104, 142, 159],
                                [108, 135, 247],
                                [53, 160, 64],
                                [112, 168, 149],
                                [110, 147, 159],
                                [56, 165, 97],
                                [54, 184, 90],
                                [110, 135, 238],
                                [100, 139, 152],
                                [103, 142, 160],
                                [57, 157, 92],
                                [58, 163, 106],
                                [59, 228, 94]])
# Training inputs are organized in a array within a 3x41 matrix
# Each array within the matrix is a set of inputs from the dataset
# Each input within the array is specific EKG variable as shown below:
# [Heart Rate, PR Interval, P Interval]

training_outputs_nn3 = np.array([[1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1]]).T
# Training outputs are organized in an array which has been transposed to a 41x1 matrix
# The first value of the output's array is the respective output for the input's first array
# An output of 0 signifies the EKG is Tachycardia
# An output of 1 signifies the EKG is Bradycardia

##### The next step after defining our training example is to initialize our weights, like accomplished in the previous neural networks.

In [ ]:
synaptic_weights_nn3 = 2 * np.random.random((3,1)) - 1
# We don't know each input's significance on the output, therefore we will assign random weights
# Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
# The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1

print('Synaptic Weights Prior Training:')
print(synaptic_weights_nn3)
# Printing the synaptic weights prior training will allow us to compare the weights post training

Synaptic Weights Prior Training:
[[ 0.29654932]
 [ 0.25689955]
 [-0.90788976]]


##### Since our normalizing function has been defined, training examples have been organized, and our synaptic weights have been intialized, we can start training the second model.

###### Once again our architecture of our neural network and method of error calculations will remain the same as the first neural netowrk. The architecture of our neural network consists of 4 features: inputs, synapses, neuron & output. The inputs in this neural network are the various values collected from a EKG. The synapses are the connections between the inputs and the neuron. The neuron is the sigmoid normalizing function that predicts our output. Finally our output is a range from 0 to 1, with any value close to zero resembling a Tachycardiac EKG and any value close to 1 resembling an Bradycardiac EKG. This neural network architecture has been pictured [here](https://drive.google.com/file/d/1HDXbnD7nKK7ZIM13lbX1IFDtUzrFgsL9/view?usp=sharing).

In [ ]:
for iteration in range(50000):
# Embeding the code below in a for loop allows us to run multiple iterations
# The value in range is the total number of iterations we want to run

  input_layer_nn3 = training_inputs_nn3
  # Relabelling training inputs as input layer to distinguish the inputs

  outputs_nn3 = sigmoid(np.dot(input_layer_nn3, synaptic_weights_nn3))
  # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
  # By using np.dot we can multiply the synaptic weight by the array of inputs

  error_nn3 = training_outputs_nn3 - outputs_nn3
  # The error is the difference between output and actual output

  weight_adjustments_nn3 = error_nn3 * sigmoid_derivative(outputs_nn3)
  # Calculated by multiplying the error and the sigmoid derivative

  synaptic_weights_nn3 += np.dot(input_layer_nn3.T, weight_adjustments_nn3)
  # Input layer must be transposed to match array
  # By using np.dot we can multiply the weight adjustments by the input layer array

  print('Synaptic Weights Post Training:')
  print(synaptic_weights_nn3)
  # Printing the synaptic weights post training will allow us to compare the weights prior training

Streaming output truncated to the last 5000 lines.
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weights Post Training:
[[-7.74484942]
 [21.64970604]
 [ 2.92339709]]
Synaptic Weig

##### The set of values printed above are the synaptic weights post training. Let's compare the synaptic weigths.

##### The synaptic weights prior to training were set to be random as we didn't know what variables contribute to tachycardia or bradycardia. However if we look at the values of the synpaptic weigths after training the values have been ranked with the most significant contributer having the highest numerical synaptic weight.

##### After running the necessary number of iterations we have derived the appropriate synaptic weights. This means we can finally pass inputs (EKG variables) with an unknown classification of tachycardic EKG or bradycardic EKG and have the nueral network predict whether the EKG is tachycardic or bradycardic.

##### In order to pass our inputs inserted through our first neural network through the third neural network we need to define a function where we can pull the EKG values from the first neural network.

In [ ]:
def compute(self, inputs):
# Defining the function that will be used to type in our own EKG values

  inputs = inputs.astype(float)
  # Since our inputs are integers we need to convert them to a float, to match our synaptic weights

  output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
  # By using np.dot we can multiply the arrays of inputs and the synaptic weights
  # The product can then be plugged into the sigmoid function to calculate the output

  return output

##### Although we want to run the same EKG inputs from our first neural network through our third nueral network we need to rewrite all the code for the third neural network within a class in order to be re-run our own EKG Values. Since we are limited by the cell layout of Google Collab, even though it is inefficient, the most appropriate solution is to rewrite the code for the third neuron above into a class in one code cell. This also requires us to treat many variables as objects. Additionally by using if statements and operators we have the model print out what the EKG reflects: Tachycardia or Bradycardia. This has been done below.

In [ ]:
class neural_network_3():

    def __init__(self):
    # We are initializing the object's attributes

        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
        # We don't know each input's significance on the output, therefore we will assign random weights
        # Since we have 6 inputs & 1 output we'll create a 6x1 matrix for the weights
        # The range of the random values will be from -1 to 1, this was set by multiplying the random numbers by 2 and subtracting 1


    def sigmoid(self, x):
    # Define the normalizing function, in this context a sigmoid function

        return 1 / (1 + np.exp(-x))
        # The standard mathematical function for a sigmoid function that returns a value between 0 & 1

    def sigmoid_derivative(self, x):
    # Define the sigmoid derivative

        return x * (1 - x)
        # The derivative of the sigmoid function in terms of x

    def train(self, training_inputs, training_outputs):
    # Define a function to run training data

        for iteration in range(500000):
        # Embeding the code below in a for loop allows us to run multiple iterations
        # The value in range is the total number of iterations we want to run

            output_nn3 = sigmoid(np.dot(input_layer_nn3, synaptic_weights_nn3))
            # The output is derived by passing the product of the input layer and synaptic weight through the sigmoid function
            # By using np.dot we can multiply the synaptic weight by the array of inputs

            error_nn3 = training_outputs - output_nn3
            # The error is the difference between output and actual output

            weights_nn3 = error_nn3 * self.sigmoid_derivative(output_nn3)
            # Calculated by multiplying the error and the sigmoid derivative

            weight_adjustments_nn3 = np.dot(training_inputs.T, weights_nn3)
            # Training inputs must be transposed to match array
            # By using np.dot we can multiply the training inputs by the weights


            self.synaptic_weights += weight_adjustments_nn3
            # Adjust the weights accordiningly

            training_inputs_nn3 = np.array([[44, 175, 42],
                                            [59, 163, 106],
                                            [163, 126, 60],
                                            [49, 145, 101],
                                            [103, 169, 85],
                                            [40, 170, 102],
                                            [124, 155, 64],
                                            [32, 162, 95],
                                            [122, 204, 72],
                                            [102, 224, 122],
                                            [42, 192, 101],
                                            [112, 178, 117],
                                            [101, 172, 90],
                                            [56, 180, 104],
                                            [53, 228, 94],
                                            [117, 141, 79],
                                            [58, 174, 39],
                                            [101, 136, 82],
                                            [51, 157, 91],
                                            [104, 121, 67],
                                            [100, 156, 172],
                                            [55, 133, 101],
                                            [56, 148, 93],
                                            [101, 147, 155],
                                            [102, 158, 177],
                                            [50, 180, 68],
                                            [57, 142, 91],
                                            [102, 156, 173],
                                            [104, 142, 159],
                                            [108, 135, 247],
                                            [53, 160, 64],
                                            [112, 168, 149],
                                            [110, 147, 159],
                                            [56, 165, 97],
                                            [54, 184, 90],
                                            [110, 135, 238],
                                            [100, 139, 152],
                                            [103, 142, 160],
                                            [57, 157, 92],
                                            [58, 163, 106],
                                            [59, 228, 94]])
            # Training inputs are organized in a array within a 6x10 matrix
            # Each array within the matrix is a set of inputs from the dataset
            # Each input within the array is specific EKG variable as shown below:
            # [Heart Rate, QRS Duration, PR Interval, T Interval, P Interval, QT Interval]

            training_outputs_nn3 = np.array([[1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1]]).T
            # Training outputs are organized in an array which has been transposed to a 10x1 matrix
            # The first value of the output's array is the respective output for the input's first array
            # An output of 0 signifies the EKG is Atrial Fibrillation
            # An output of 1 signifies the EKG is Tachycardia/Bradycardia

    def compute(self, inputs):
    # Define compute function which allows to pass new EKG values through the neural network

        inputs = inputs.astype(float)
        # Since weights are floats all inputs need to be floats as well

        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        # Run the inputs through the sigmoid function after weight adjustment

        return output


neural_network = neural_network_3()
# Rename neural network class to neural network for ease of use

neural_network.train(training_inputs_nn3, training_outputs_nn3)
# Intializes the training of the training data


print("Output:")

final_output = (neural_network.compute(np.array([heart_rate, PR_interval, P_interval])))
# Computes new EKG inputs and classifies it either 0 or 1

print(final_output)
# Prints the final value on a scale of 0 and 1

if final_output < 0.2:
  print('EKG is Tachycardic')
  # Prints EKG is Tachycardic Fibrillation if value less than 0.2

if final_output > 0.8:
  print('EKG is Bradycardic')
  # Prints EKG is Bradycardic if value greater than 0.8

Output:
[0.99999001]
EKG is Bradycardic
